messages:
  hello: Hello world!
http:
  rootPath: /method/*
database:
  driverClass: com.mysql.jdbc.Driver
  user: courses
  password: hLvKfxEX5sTaEUzu
  url: jdbc:mysql://localhost/courses?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false